apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-app
spec:
  selector:
    matchLabels:
      app: {{ .Values.labelSelector }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 80