services:
    jenkins:
        build: ./jenkins/master
        image: jenkins/jenkins:latest
        container_name: jenkins
        ports:
            - '8081:8080'
            - '50000:50000'
        volumes:
            - /Users/reanir/repo/devops-final-project/spring-petclinic/jenkins/jenkins/jenkins_jobs:/var/jenkins_home/jobs
        networks: 
            - jb
    jenkins-slave:
        build: ./jenkins/slave
        image: jenkins-jb/slave:1.0
        platform: linux/amd64
        # Removed container name to support scale out option 
        #container_name: jenkins-slave 
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - ./volume:/home/jenkins # Avoid mysql volume mount issue
        networks: 
        - jb
        depends_on:
            - jenkins

networks: 
  jb: